### ISSUE TITLE
specify precision for degree/decimal conversion

### ISSUE THREAD

**Issue by snoyes** [nasa/HyperInSPACE#3]
https://github.com/nasa/HyperInSPACE/blob/951206f742dd280db7f8d4ad2722bdce6f55a2c5/Source/Utilities.py#L177-L193

It is reasonable to expect that `ddToDm(dmToDd(n)) == n` for all n. However, for `n = 31` (that is, 0 degrees 31 minutes), this equality does not hold because of the inexact nature of floating point numbers - the value differs from expected by 3.5e-15 (it may depend on hardware and implementation). Curiously, this behavior does not occur for <anything other than 0> degrees 31 minutes.

I recommend that `dmToDd` accept an optional `precision` parameter (defaulting to, say, 3 or 6 decimal places) and round the results accordingly.

**Comment by oceancolorcoder** [comment]
Pull request merged to master, and thanks again.
