### ISSUE TITLE
Class-based cals L1B

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperInSPACE#35]
L1B pathway for class-based characterization and calibration is incomplete for SeaBird. For TriOS, this path is coded to do the same thing as factory calibration (is this intentional?)

**Comment by oceancolorcoder** [comment]
Complete class-based characterizations provided by Tartu. Code needs to be updated to accommodate new filenames/formats.

**Comment by AlexisDeru** [comment]
I have a working version locally, class-based file can be ingested automatically, but it still requires sensor specific "RADCAL" files. Waiting for a consortium decision before going forward

**Comment by oceancolorcoder** [comment]
Resolved with f6bbfa1
