### ISSUE TITLE
negative degrees not correctly converted

### ISSUE THREAD

**Issue by snoyes** [nasa/HyperInSPACE#4]
https://github.com/nasa/HyperInSPACE/blob/951206f742dd280db7f8d4ad2722bdce6f55a2c5/Source/Utilities.py#L187-L193

-0.05 degrees is 3 minutes (South or West).
`ddToDm(-0.05)` returns 3.0, meaning 3 minutes (North or East).

-1.05 degrees is 1 degree 3 minutes (South or West).
`ddToDm(-1.05)` returns -97.0, meaning 97 minutes (South or West), equivalent to 1 degree 37 minutes.

**Comment by oceancolorcoder** [comment]
Thank you for pointing this out. This method is a very old and long uncalled remnant and will be removed.

**Comment by oceancolorcoder** [comment]
I changed my mind and left it in for testing. Correction implemented with patch-1 pull request. Thanks again.
